version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  huey:
    build: .
    volumes:
      - .:/app
    depends_on:
      - redis
      - web
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    command: ["huey_consumer", "tasks.huey"]

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --save 60 1 --dir /data

volumes:
  redis_data:
