---
# Loki ConfigMap with the fixed configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
  namespace: default
  labels:
    app.kubernetes.io/name: loki
data:
  config.yaml: |
    auth_enabled: true
    server:
      http_listen_port: 3100
      grpc_listen_port: 9095
    common:
      path_prefix: /var/loki
      replication_factor: 1
      storage:
        s3:
          access_key_id: root-user
          bucketnames: chunks
          endpoint: loki-minio.default.svc:9000
          insecure: true
          s3forcepathstyle: true
          secret_access_key: supersecretpassword
    frontend:
      scheduler_address: ""
    compactor:
      working_directory: /var/loki/compactor
    distributor:
      ring:
        kvstore:
          store: memberlist
    ingester:
      lifecycler:
        ring:
          kvstore:
            store: memberlist
          replication_factor: 1
      chunk_idle_period: 30m
      chunk_block_size: 262144
      chunk_encoding: snappy
      chunk_retain_period: 1m
      wal:
        dir: /var/loki/wal
    limits_config:
      allow_structured_metadata: false
      reject_old_samples: true
      reject_old_samples_max_age: 168h
      max_cache_freshness_per_query: 10m
      split_queries_by_interval: 15m
      max_query_parallelism: 32
      max_query_series: 10000
      cardinality_limit: 100000
      max_streams_per_user: 10000
      max_line_size: 256000
      max_entries_limit_per_query: 5000
      max_label_names_per_series: 30
      max_label_name_length: 1024
      max_label_value_length: 2048
    memberlist:
      join_members:
        - loki-0.loki-headless.default.svc.cluster.local
    query_range:
      align_queries_with_step: true
      max_retries: 5
      cache_results: true
      results_cache:
        cache:
          memcached_client:
            addresses: dnssrvnoa+_memcached-client._tcp.loki-results-cache.default.svc
            consistent_hash: true
            timeout: 500ms
            update_interval: 1m
    ruler:
      storage:
        type: local
        local:
          directory: /var/loki/rules
      ring:
        kvstore:
          store: memberlist
      rule_path: /var/loki/rules-temp
      alertmanager_url: http://alertmanager.default.svc.cluster.local:9093
      external_url: https://alertmanager.example.com
    schema_config:
      configs:
        - from: 2023-01-01
          store: boltdb-shipper
          object_store: s3
          schema: v12
          index:
            prefix: loki_index_
            period: 24h
    storage_config:
      boltdb_shipper:
        active_index_directory: /var/loki/index
        cache_location: /var/loki/cache
        cache_ttl: 168h
      aws:
        s3: null
    chunk_store_config:
    table_manager:
      retention_deletes_enabled: false
      retention_period: 0s
    query_scheduler:
      max_outstanding_requests_per_tenant: 4096
    frontend_worker:
      frontend_address: ""
